package main

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"time"

	light_strip "github.com/slidebolt/sdk-entities/light_strip"
	"github.com/slidebolt/sdk-types"
)

func groupsDevice() types.Device {
	return types.Device{
		ID:         "groups",
		SourceID:   "groups",
		SourceName: "Automation Groups",
	}
}

// automationMeta holds the parsed JSON blob stored in entity.Meta["PluginAutomation:<group>"].
type automationMeta struct {
	Domain string `json:"domain,omitempty"`
	Index  *int   `json:"index,omitempty"`
	Row    *int   `json:"row,omitempty"`
	Col    *int   `json:"col,omitempty"`
}

// stripMember records a single positional member of a light_strip virtual entity.
type stripMember struct {
	Index    int    `json:"index"`
	PluginID string `json:"plugin_id"`
	DeviceID string `json:"device_id"`
	EntityID string `json:"entity_id"`
}

// buildAutoGroups creates virtual group entities from PluginAutomation labels.
//
// Two kinds of virtual entity are produced:
//   - Broadcast groups: no member carries positional meta (existing behavior).
//   - Strip groups: at least one member has an "index" in its meta blob;
//     these get domain "light_strip" and a sorted strip_members meta blob.
func buildAutoGroups(matches []types.Entity, log *slog.Logger) ([]types.Entity, error) {
	if log == nil {
		log = slog.Default()
	}
	log.Debug("groups: registry returned entities", "total", len(matches))

	type broadcastSample struct {
		domain  string
		actions []string
	}
	type groupAccumulator struct {
		broadcast *broadcastSample
		strip     []stripMember
	}

	accumulators := map[string]*groupAccumulator{}

	for _, m := range matches {
		vals := m.Labels["PluginAutomation"]
		if len(vals) == 0 {
			continue
		}
		// Exclude group entities already generated by this device to avoid cycles.
		if m.PluginID == "plugin-automation" && m.DeviceID == "groups" {
			continue
		}
		log.Debug("groups: entity has PluginAutomation label",
			"entity_id", m.ID,
			"device_id", m.DeviceID,
			"plugin_id", m.PluginID,
			"labels", vals,
		)
		for _, g := range vals {
			g = strings.TrimSpace(g)
			if g == "" {
				continue
			}
			if accumulators[g] == nil {
				accumulators[g] = &groupAccumulator{}
			}
			acc := accumulators[g]

			// Parse optional meta blob for this entity/group membership.
			var meta automationMeta
			if raw, ok := m.Meta["PluginAutomation:"+g]; ok {
				if err := json.Unmarshal(raw, &meta); err != nil {
					log.Warn("groups: failed to parse meta blob",
						"entity_id", m.ID, "group", g, "err", err)
				}
			}

			if meta.Index != nil {
				// Positional member → contributes to a strip group.
				acc.strip = append(acc.strip, stripMember{
					Index:    *meta.Index,
					PluginID: m.PluginID,
					DeviceID: m.DeviceID,
					EntityID: m.ID,
				})
			} else {
				// Non-positional member → contributes to a broadcast group.
				// Only the first-seen entity sets the domain/actions.
				if acc.broadcast == nil {
					domain := strings.TrimSpace(m.Domain)
					if meta.Domain != "" {
						domain = meta.Domain
					}
					if domain == "" {
						domain = "switch"
					}
					actions := append([]string(nil), m.Actions...)
					if len(actions) == 0 {
						actions = []string{"turn_on", "turn_off"}
					}
					acc.broadcast = &broadcastSample{domain: domain, actions: actions}
				}
			}
		}
	}

	if len(accumulators) == 0 {
		log.Info("groups: no PluginAutomation labels found — no groups to build")
		return nil, nil
	}

	names := make([]string, 0, len(accumulators))
	for name := range accumulators {
		names = append(names, name)
	}
	sort.Strings(names)
	log.Info("groups: building", "groups", names)

	out := make([]types.Entity, 0, len(names))
	for _, name := range names {
		acc := accumulators[name]

		if len(acc.strip) > 0 {
			// Strip group: at least one positional member.
			members := make([]stripMember, len(acc.strip))
			copy(members, acc.strip)
			sort.Slice(members, func(i, j int) bool {
				return members[i].Index < members[j].Index
			})
			membersJSON, err := json.Marshal(members)
			if err != nil {
				return nil, fmt.Errorf("marshal strip_members for %q: %w", name, err)
			}
			out = append(out, types.Entity{
				ID:        "group-" + normalizeID(name),
				DeviceID:  "groups",
				Domain:    light_strip.Type,
				LocalName: name,
				Actions:   light_strip.SupportedActions(),
				Labels: map[string][]string{
					"Group":                {name},
					"virtual_source_query": {fmt.Sprintf("?label=PluginAutomation:%s", name)},
				},
				Meta: map[string]json.RawMessage{
					"strip_members": membersJSON,
				},
				// CommandQuery fans out broadcast commands to every member light.
				// CommandFilter excludes set_segment so it falls through to OnCommand
				// for positional translation.
				CommandQuery: &types.SearchQuery{
					Labels: map[string][]string{"PluginAutomation": {name}},
				},
				CommandFilter: light_strip.BroadcastActions(),
				Data: types.EntityData{
					SyncStatus: types.SyncStatusSynced,
					UpdatedAt:  time.Now().UTC(),
				},
			})
		} else if acc.broadcast != nil {
			// Broadcast group: no positional members.
			out = append(out, types.Entity{
				ID:        "group-" + normalizeID(name),
				DeviceID:  "groups",
				Domain:    acc.broadcast.domain,
				LocalName: name,
				Actions:   acc.broadcast.actions,
				Labels: map[string][]string{
					"Group":                {name},
					"virtual_source_query": {fmt.Sprintf("?label=PluginAutomation:%s", name)},
				},
				CommandQuery: &types.SearchQuery{
					Labels: map[string][]string{"PluginAutomation": {name}},
				},
				Data: types.EntityData{
					SyncStatus: types.SyncStatusSynced,
					UpdatedAt:  time.Now().UTC(),
				},
			})
		}
	}
	return out, nil
}

func normalizeID(s string) string {
	s = strings.TrimSpace(strings.ToLower(s))
	if s == "" {
		return "unnamed"
	}
	var b strings.Builder
	prevDash := false
	for _, r := range s {
		ok := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if ok {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash {
			b.WriteByte('-')
			prevDash = true
		}
	}
	id := strings.Trim(b.String(), "-")
	if id == "" {
		return "unnamed"
	}
	return id
}
