package main

import (
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"time"

	"github.com/slidebolt/sdk-types"
)

func groupsDevice() types.Device {
	return types.Device{
		ID:         "groups",
		SourceID:   "groups",
		SourceName: "Automation Groups",
	}
}

// buildAutoGroups creates one virtual group entity per distinct PluginAutomation label.
func buildAutoGroups(matches []types.Entity, log *slog.Logger) ([]types.Entity, error) {
	if log == nil {
		log = slog.Default()
	}
	log.Debug("groups: registry returned entities", "total", len(matches))

	type sample struct {
		domain  string
		actions []string
	}
	groupSamples := map[string]sample{}
	for _, m := range matches {
		vals := m.Labels["PluginAutomation"]
		if len(vals) == 0 {
			continue
		}
		// Exclude group entities already generated by this device to avoid cycles.
		if m.PluginID == "plugin-automation" && m.DeviceID == "groups" {
			continue
		}
		log.Debug("groups: entity has PluginAutomation label",
			"entity_id", m.ID,
			"device_id", m.DeviceID,
			"plugin_id", m.PluginID,
			"labels", vals,
		)
		for _, g := range vals {
			g = strings.TrimSpace(g)
			if g == "" {
				continue
			}
			if _, ok := groupSamples[g]; !ok {
				groupSamples[g] = sample{
					domain:  strings.TrimSpace(m.Domain),
					actions: append([]string(nil), m.Actions...),
				}
			}
		}
	}

	if len(groupSamples) == 0 {
		log.Info("groups: no PluginAutomation labels found — no groups to build")
		return nil, nil
	}

	names := make([]string, 0, len(groupSamples))
	for name := range groupSamples {
		names = append(names, name)
	}
	sort.Strings(names)
	log.Info("groups: building", "groups", names)

	out := make([]types.Entity, 0, len(names))
	for _, name := range names {
		s := groupSamples[name]
		domain := s.domain
		if domain == "" {
			domain = "switch"
		}
		actions := append([]string(nil), s.actions...)
		if len(actions) == 0 {
			actions = []string{"turn_on", "turn_off"}
		}
		out = append(out, types.Entity{
			ID:        "group-" + normalizeID(name),
			DeviceID:  "groups",
			Domain:    domain,
			LocalName: name,
			Actions:   actions,
			Labels: map[string][]string{
				"Group":                {name},
				"virtual_source_query": {fmt.Sprintf("?label=PluginAutomation:%s", name)},
			},
			Data: types.EntityData{
				SyncStatus: types.SyncStatusSynced,
				UpdatedAt:  time.Now().UTC(),
			},
		})
	}
	return out, nil
}

func normalizeID(s string) string {
	s = strings.TrimSpace(strings.ToLower(s))
	if s == "" {
		return "unnamed"
	}
	var b strings.Builder
	prevDash := false
	for _, r := range s {
		ok := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if ok {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash {
			b.WriteByte('-')
			prevDash = true
		}
	}
	id := strings.Trim(b.String(), "-")
	if id == "" {
		return "unnamed"
	}
	return id
}
